{
    "name":"testTheme",
    "type":"theme",
    "colors": {
        "WHITE": "#FFFFFF",
        "BLACK": "#000000",
        "Purple": "#921",
        "cleanWhite": "#F5F5F5",
        "spottr": "#F04C44",
        "Clear": "#0000",
    },
    "images": {
        "Image1": "Path1.png",
        "Image2": "Path2.png"
    },
    "kvp": {
        "PointlessProperty": "PointlessValue",
        "UsefulProperty": "UsefulValue"
    },
    "gradients": {
        "Spottr":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#f1592a","weight":1.0},
                {"color":"#ef4036","weight":0.0}
            ]
        },
        "Meadow":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#AFD044","weight":1.0},
                {"color":"#43B34E","weight":0.0}
            ]
        },
        "Abyss":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#1A75B8","weight":1.0},
                {"color":"#272662","weight":0.0}
            ]
        },
        "Sky":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#9FDCF7","weight":1.0},
                {"color":"#1EB2EE","weight":0.0}
            ]
        },
        "Inferno":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#ED413E","weight":1.0},
                {"color":"#BF2232","weight":0.0}
            ]
        },
        "Mocha":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#B17C52","weight":1.0},
                {"color":"#5F4023","weight":0.0}
            ]
        },
        "Tranquil":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#35A6AF","weight":1.0},
                {"color":"#71B496","weight":0.0}
            ]
        },
        "Nebula":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#D65068","weight":1.0},
                {"color":"#323B8D","weight":0.0}
            ]
        },
        "Ash":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#808284","weight":1.0},
                {"color":"#58585A","weight":0.0}
            ]
        },
        "Citrus":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#FAAF4D","weight":1.0},
                {"color":"#F59432","weight":0.0}
            ]
        },
        "Cedar":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#149348","weight":1.0},
                {"color":"#0B693B","weight":0.0}
            ]
        },
        "Nightfall":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#272461","weight":1.0},
                {"color":"#293A8D","weight":0.0}
            ]
        },
        "Oceanview":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#22A79D","weight":1.0},
                {"color":"#EB423E","weight":0.0}
            ]
        },
        "Scorch":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#FAAE4C","weight":1.0},
                {"color":"#EE453E","weight":0.0}
            ]
        },
        "Mint":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#29B68D","weight":1.0},
                {"color":"#32B478","weight":0.0}
            ]
        },
        "Cream":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#E0A488","weight":1.0},
                {"color":"#C3996F","weight":0.0}
            ]
        },
        "Princess":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#E02977","weight":1.0},
                {"color":"#D8215E","weight":0.0}
            ]
        },
        "Sanguine":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#912835","weight":1.0},
                {"color":"#6E2B37","weight":0.0}
            ]
        },
        "Royal":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#912D8D","weight":1.0},
                {"color":"#282460","weight":0.0}
            ]
        },
        "Arctic":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#8FBDE3","weight":1.0},
                {"color":"#D0D2D4","weight":0.0}
            ]
        },
        "Pebble":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#C2B49C","weight":1.0},
                {"color":"#9A867B","weight":0.0}
            ]
        },
        "Hive":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#F5EC48","weight":1.0},
                {"color":"#FAB14C","weight":0.0}
            ]
        },
        "Onyx":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#383839","weight":1.0},
                {"color":"#020202","weight":0.0}
            ]
        },
        "Clean":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"cleanWhite","weight":1.0},
                {"color":"cleanWhite","weight":0.25},
                {"color":"#9C9C9C","weight":0.0}
            ]
        },
        "Ion":{
            "type":"linear",
            "angle":90,
            "colorWeights": [
                {"color":"#33ACE0","weight":1.0},
                {"color":"#1274B9","weight":0.0}
            ]
        },
        "OceanviewTest":{
            "type":"linear",
            "angle":75,
            "colorWeights": [
                {"color":"#1CA59B","weight":1.0},
                {"color":"#FFFFFF","weight":0.25},
                {"color":"#EA463E","weight":0.0}
            ]
        }

    },
    "styles": {
        "background": { "type": "color", "name": "#F5F5F5" },
        "buttonStats": {
            "norm": "#F5F5F5",
            "down": "#8C8C8C" ,
            "selected": "#E8E8E8" ,
            "disabled": "#525252"
        },
        "textColor": "#F5F5F5",
        "font": { "name": "Helvetica Neue", "size": 12 },
        "textAlignment": "left",
        "cornerRadius": 0.0,
        "styleMargin": {"width": 10.0, "height": 10.0},
        
        "children":{
            "label": {
                "background": { "type": "color", "name": "#000000FF" },
                "textAlignment": "left"
            },
            "titleBar": {
                "font": { "size": 18 }
            },
            "cls_secondaryStyle": {
                "background": { "type": "color", "name": "#F04C44" },
                "styleMargin": {"height": 7.0}
            },
            "button":{
                "background": { "type": "color", "name": "#F5F5F5" }
            },
            "body":{
                "background": { "type": "color", "name": "#000" }
            }
        }
    }
}
